### ISSUE TITLE
Currency Support?

### ISSUE THREAD

**Issue by guatedude2** [fabiomcosta/jquery-meiomask#5]
Are you planning on expaning it so that it uses Currency support like for example suffix and prefix, like Jermy Dorn extended in his example here: http://jeremydorn.com/demos/meio.html

Don't want to use his because it's version 1.0.1

**Comment by jamesj2** [comment]
I don't want to resurrect this.  Just want to add a possible solutions for others that find this issue.  
Here's what I use to add US currency after the meiomask has been loaded and before using setMask().
```
if (typeof $.mask.masks === 'object') {
    $.extend($.mask.signals, {'$': '$'});
    $.extend($.mask.masks, {'currency-us': {mask: '99.999,999,999,999', type: 'reverse', defaultValue: '$'}});
}
```
