### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by jt3k** [fabiomcosta/jquery-meiomask#75]
whereis locate the documentation?
or i needs look in the sources ?

**Comment by johnvoloski** [comment]
Hi @jt3k , you can find documentation on [Wiki](https://github.com/fabiomcosta/jquery-meiomask/wiki) and some examples on [Visual Tests](https://github.com/fabiomcosta/jquery-meiomask/blob/master/spec/visual/meiomask.html)

**Comment by jt3k** [comment]
Ok, thnx!
