### ISSUE TITLE
IE11 (edge) number input reversing number on input

### ISSUE THREAD

**Issue by m-montoya** [fabiomcosta/jquery-meiomask#76]
Only found this within IE11 (edge). < IE11, Chrome and FF seem fine. When I have the following code defined like so

`$('.grid input').setMask({ mask: '999,999,999,999', type: 'reverse' });`

And I go to type 123 into the input field, it displays 321. Removing 'reverse' enables me to type 123 but I loose the correct masking for the thousand placement.

**Comment by Brookd23** [comment]
Ever find a fix for this? We're experiencing the same issue and have had no luck tracking down a fix.

**Comment by camilaguidi** [comment]
We're experiencing the same issue. Any fix for this?

**Comment by camilaguidi** [comment]
We're experiencing the same issue. Any fix for this?

**Comment by ghost** [comment]
We just stopped supporting IE 11. IE 11 is dead, gone and no one should be using it any more.
